Added configurable Google Tag Manager domain.
netzstrategen/wordpress-shop-analytics pull request #56
Opened 2022-06-30 10:50 UTC by alinistrate

### Ticket
- [Make GTM script domain configurable in plugin settings](https://app.asana.com/0/1201940451841784/1202508895538464)

2022-07-05 09:16 UTC, bogdanarizancu approved these changes

2022-07-18 12:56 UTC, sun requested changes

2022-07-18 12:56 UTC, sun commented on src/Plugin.php
> +    $embed_url_domain = get_option('shop_analytics_url_domain') ?: 'www.googletagmanager.com';
See https://github.com/netzstrategen/wordpress-cookie-consent/pull/25#discussion_r923313235
```suggestion
    $embed_url_domain = get_option('shop_analytics_gtm_domain') ?: 'www.googletagmanager.com';
```

2022-07-18 12:56 UTC, sun commented on templates/settings.php
> +            maxlength="40"
```suggestion
```

2022-07-18 12:56 UTC, sun commented on templates/settings.php
> +          <label for="shop-analytics-url-domain"><?= __('Script embed URL domain', Plugin::L10N) ?></label>
```suggestion
          <label for="shop-analytics-url-domain">Google Tag Manager Domain</label>
```

2022-07-19 08:46 UTC, sun requested changes
The other instances of the names were not updated accordingly.

2022-07-19 08:46 UTC, sun commented on src/Admin.php
> +    register_setting('shop-analytics-settings', 'shop_analytics_url_domain');
```suggestion
    register_setting('shop-analytics-settings', 'shop_analytics_gtm_domain');
```

2022-07-19 08:46 UTC, sun commented on src/Plugin.php
> +    $embed_url_domain = get_option('shop_analytics_url_domain') ?: 'www.googletagmanager.com';
```suggestion
    $embed_url_domain = get_option('shop_analytics_gtm_domain') ?: 'www.googletagmanager.com';
```

2022-07-19 08:46 UTC, sun commented on templates/settings.php
> +          <label for="shop-analytics-url-domain">Google Tag Manager Domain</label>
```suggestion
          <label for="shop-analytics-gtm-domain">Google Tag Manager Domain</label>
```

2022-07-19 08:46 UTC, sun commented on templates/settings.php
> +            value="<?= esc_attr(get_option('shop_analytics_url_domain')) ?>"
```suggestion
            id="shop-analytics-gtm-domain"
            name="shop_analytics_gtm_domain"
            type="text"
            size="50"
            value="<?= esc_attr(get_option('shop_analytics_gtm_domain')) ?>"
```

2022-07-19 17:57 UTC, sun approved these changes
Thank you! 👍  Please squash-merge using the PR title as commit message.

2022-07-19 17:57 UTC, merged